coder/terraform-provider-coder

docs/resources/agent.md
examples/resources/coder_agent/resource.tf
internal/provider/provider.go

The "CODER_TOKEN" variable will be used for user-sessions,
which are required to distinguish between agent sessions.

feat: Update "CODER_TOKEN" to "CODER_AGENT_TOKEN"

---

examples/resources/coder_app/resource.tf

fix: (example) coder_app uses relative_path

---

go.mod
go.sum
internal/provider/provider.go
internal/provider/provider_test.go

fix: Add check for duplicate metadata keys

---

docs/resources/agent.md
provider/agent.go
provider/agent_test.go

Related: https://github.com/coder/coder/issues/4678

feat: Add connection_timeout and troubleshooting_url to agent

---

.github/workflows/cla.yaml

related to https://github.com/coder/coder/pull/4354
**Requires the token to be configured before we can merge - see below**

chore(cla): implement coder.com/cla

---

.github/workflows/test.yml
examples/resources/coder_parameter/resource.tf

- Add linting for fmt and gen
- Update Go version
- Add more TF versions to test matrix
Lint fmt:
Lint gen:

ci: Add fmt and gen linting

---

docs/data-sources/parameter.md
docs/data-sources/workspace.md
provider/workspace.go

This was requested by multiple community members in Discord: https://discord.com/channels/747933592273027093/1071182088490987542/1071182088490987542

feat: add `owner_oidc_access_token` to `coder_workspace` data source

---

docs/data-sources/parameter.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6852
This PR introduces a new property to `coder_parameter` - `display_name`.

feat: Add display_name to coder_parameter

---

docs/data-sources/workspace.md
provider/workspace.go
provider/workspace_test.go

fixes the TF side of https://github.com/coder/coder/issues/6354

feat: add session token data source

---

.github/workflows/test.yml

ci: include terraform 1.5.* to tests

---

docs/data-sources/workspace.md
provider/workspace.go
provider/workspace_test.go

implements the TF portion of https://github.com/coder/coder/issues/9149

feat: add template_id and template_name to workspace data source

---

provider/agent.go
provider/agent_test.go

resolves [#9713](https://github.com/coder/coder/issues/9713)

fix: add error detail for duplicate agent metadata key

---

docs/data-sources/workspace.md
provider/workspace.go
provider/workspace_test.go

Related: https://github.com/coder/coder/issues/9883
This PR introduces another workspace resource property - owner's name.

feat: add owner name to workspace

---

docs/data-sources/external_auth.md
provider/externalauth.go
provider/externalauth_test.go

feat: add `optional` property to `coder_external_auth`

---

.devcontainer/devcontainer.json

chore: add devcontainer config

---

provider/provider_test.go
provider/workspace_owner.go

Follow-up of https://github.com/coder/terraform-provider-coder/pull/230

fix: provider: coder_workspace_owner: avoid setting null values

---

docs/index.md
templates/index.md.tmpl

backport(docs): add description to provider index page

---

main.go
pprof_unix.go
pprof_windows.go

* chore: add http/pprof server over unix socket for debug

chore: add http/pprof server over unix socket for debug (#295)

---

.github/workflows/release.yml
.github/workflows/test.yml

Fixes https://github.com/coder/terraform-provider-coder/issues/252

ci: run integration tests before release

---

.github/workflows/release.yml

goreleaser does this apparently

ci: rm unused action

---

.goreleaser.yml

Reverts coder/terraform-provider-coder#319

Revert "fix(.goreleaser.yml): use semver to sort git tags"

---

.github/workflows/release.yml
.goreleaser.yml

Should solve the issue seen in: https://github.com/coder/terraform-provider-coder/actions/runs/13413247170

chore: set GoReleaser version to 2 in config

---

.github/workflows/test.yml

chore: include terraform 1.11.* in tests

---

main.go

https://developer.hashicorp.com/terraform/plugin/debugging#starting-a-provider-in-debug-mode
https://developer.hashicorp.com/terraform/plugin/sdkv2/debugging

feat: add the option to debug the coder terraform provider

---

docs/resources/app.md
provider/app.go
provider/app_test.go

Part of https://github.com/coder/coder/issues/8237

feat: add `group` attribute to `coder_app` resource
