coder/terraform-provider-coder

docs/data-sources/agent_script.md
docs/data-sources/workspace.md
docs/resources/agent.md
internal/provider/provider.go
internal/provider/provider_test.go

This enables explicit definition of auth type, so the agent
doesn't misinterpret the running environment.
This also adds "username" and "name" properties to "coder_workspace"
to allow for pretty resource naming inside a cloud.

feat: Add auth property to coder_agent_script

---

docs/resources/agent.md
examples/resources/coder_agent/resource.tf
internal/provider/provider.go
internal/provider/provider_test.go

This allows specifying where a shell will be opened
when SSH'ing into a workspace.

feat: Add "dir" option to "coder_agent"

---

internal/provider/provider.go

Users can optionally set "CODER_URL" if they want to force the
CLI to use a specific endpoint, but this should remain optional.
Forcing this to be set disallows users from using a different
Coder deployment inside of their workspace.

feat: Rename "CODER_URL" to "CODER_AGENT_URL"

---

docs/data-sources/workspace.md
docs/resources/agent.md
docs/resources/app.md
internal/provider/provider.go

This allows for 32-bit arm to be used with Coder.

fix: Add "arm" architecture

---

Makefile
docs/resources/agent.md
docs/resources/agent_instance.md
docs/resources/app.md
examples/resources/coder_app/resource.tf
internal/provider/provider.go
internal/provider/provider_test.go

This adds a `path` parameter that specifies whether the URL
provided will be accessed via the wildcard or relative path.

feat: Add path-based routing for applications

---

docs/data-sources/workspace.md
internal/provider/provider.go
internal/provider/provider_test.go

This PR adds a new attribute to the `coder_workspace` data source: `owner_email`, which is populated from the `CODER_WORKSPACE_OWNER_EMAIL` environment variable.

Add data source attribute for owner email address

---

.github/workflows/release.yml

The `.github/workflows/release.yml` workflow is currently broken by a Github change, which caused the v0.4.3 release to fail: hashicorp/ghaction-import-gpg#11
Since the `hashicorp/ghaction-import-gpg` fork is deprecated, this PR follows the recommendation to switch to the upstream `crazymax/ghaction-import-gpg` action, which has a slightly different syntax for its parameters.

Use upstream ghaction-import-gpg to fix release workflow

---

docs/data-sources/workspace.md
internal/provider/provider.go
internal/provider/provider_test.go

This allows our Docker template to use a custom host with the correct port.

feat: Expose access_port on coder_workspace to allow for alternative hosts

---

docs/data-sources/workspace.md
docs/index.md
internal/provider/provider.go
internal/provider/provider_test.go

This allows a host override, which is useful for running Docker
containers that need to access the same deployment port, but on
`host.docker.internal` as the hostname.
It also removes access port, which was released a few days ago in hopes of
solving the same problem, but never really did. It doesn't seem likely to
be used yet, so it feels safe to remove.

fix: Add custom host for access URL and remove access port

---

docs/data-sources/workspace.md
docs/index.md
internal/provider/provider.go
internal/provider/provider_test.go

Reverts coder/terraform-provider-coder#40

Revert "fix: Add custom host for access URL and remove access port"

---

internal/provider/provider.go
internal/provider/provider_test.go

Related to https://github.com/coder/coder/issues/3450

feat: Add option to hide resources from the UI

---

internal/provider/provider.go
internal/provider/provider_test.go

Related to https://github.com/coder/coder/issues/3487

feat: Add icon to coder_metadata resource

---

docs/resources/agent.md
docs/resources/metadata.md
internal/provider/provider.go

This resolves a race condition where an old agent could be updated and connected to before the new agent was registered.

fix: Regenerate agent token on each run

---

internal/provider/provider.go

This will protect users from being allow to set the `healthcheck` block more than once.

chore: set MaxItems to 1 for app healthcheck

---

docs/resources/app.md

The url of the icons in the github repository and the built-in icon string have been updated in documentation

fix icon error in documentation

---

docs/resources/app.md
examples/resources/coder_app/resource.tf
provider/app.go
provider/app_test.go

- Adds new required `slug` property to `coder_app`
- Must match a regex that ensures the slug is hostname-safe
- Adds new property `display_name` to `coder_app`
- Deprecates `name` in favor of `display_name` in `coder_app`
coder/coder#4573

feat: add slug to app, rename name to display_name

---

docs/resources/metadata.md
examples/resources/coder_metadata/resource.tf
provider/metadata.go
provider/metadata_test.go

Iffy on whether to call it `quota_cost` or `cost`. I'm leaning `cost` because it's shorter, and we may use these fields to show analytics even when quotas are disabled.

Add cost field to resource_metadata

---

docs/resources/agent.md
provider/agent.go
provider/agent_test.go

This change allows us to enable better feature parity with OpenSSH by
being able to display a message when users login. This is useful for
template authors who want to inform their users about changes or
reporting about the state of the workspace.
I did consider if we should turn this into a script, like:
```tf
motd_script = <<-EOS
cat /etc/motd
EOS
```
But while this is flexible, it raises questions like how often should we run it, sould we run it on every query, what if it takes a long time to execute, etc. For this reason we're sticking with the simplicity of a single file and making it the responsibility of the author to start a service to update its content, where required.
This feature could be expanded to support things like VSCode/JetBrains extensions as well, to surface the …

feat: Add motd_file to coder_agent

---

docs/resources/agent.md
provider/agent.go
provider/agent_test.go

Issue: https://github.com/coder/coder/issues/4677
This PR introduces a new parameter - the shutdown script. The script is intended to be executed before the agent is stopped, before the [networking is shut down](https://github.com/coder/coder/blob/main/agent/agent.go#L930).

feat: Add support for shutdown_script

---

docs/resources/app.md
docs/resources/metadata.md
provider/app.go
provider/app_test.go

This is a feature request from coder/v2-customers#9.

feat: allow apps to have external urls

---

docs/resources/app.md
docs/resources/metadata.md
examples/resources/coder_app/resource.tf
provider/app.go
provider/metadata.go
provider/metadata_test.go

fix: update docs icon paths to be `/icon/`

---

docs/resources/agent.md
provider/agent.go
provider/agent_test.go

Ref: https://github.com/coder/coder/issues/5749

feat: Add `startup_script_timeout` and `delay_login_until_ready`

---

examples/resources/coder_app/resource.tf
examples/resources/coder_parameter/resource.tf
provider/examples_test.go
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/5574
Changes:
* fix: typo in `coder_app` example
* fix: invalid parameter definition in `coder_parameter` example
* feat: show `Validation.Error` when regexp doesn't match
* feat: test `coder_parameter` example

feat: use validation error while parsing `coder_parameter`

---

examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/5574
Related: https://github.com/coder/coder/issues/5978
This PR adds a new validation property `monotonic` to the `coder_parameter`. Unfortunately, we can only validate the format within the Terraform runner, but a comparison of values, current and new, will be performed on the `coderd` API level.

feat: Validate monotonicity for coder_parameter

---

examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/5931
This PR improves tests to present that the Markdown format is acceptable for the parameter description.
~This PR introduces a new Markdown property to render rich descriptions, with Markdown tags included (see example).~
~Comment:
I admit that I wanted to use the `description` and then strip Markdown tags from descriptions in CLI, but when I looked at the [logic](https://github.com/stiang/remove-markdown/blob/main/index.js) required to perform this (rewritten to Go), I decided to KISS and use a dedicated property, that is only processed by the site.~

test: parameter description contains Markdown

---

docs/data-sources/parameter.md
docs/resources/agent.md
provider/agent.go
provider/agent_test.go

Ref: https://github.com/coder/coder/pull/6139

feat: Add `shutdown_script_timeout`

---

docs/index.md
examples/resources/coder_parameter/resource.tf
provider/provider.go

Related: https://github.com/coder/coder/issues/5980
This PR introduces a feature flag to enable managed template-wide variables. The flag is required to select the processing strategy - either use legacy Parameter Schema or new template variables ([under development](https://github.com/coder/coder/pull/6134)).
Comment:
I had to add this flag as `terraform` complains:
```
> Upload "mtojek/docker-rich"? (yes/no) yes
✔ Queued [571ms]
✔ Setting up [1ms]
✔ Parsing template parameters [60ms]
⧗  Detecting persistent resources
Terraform 1.2.6
Error: Unsupported argument
An argument named "feature_use_managed_variables" is not expected here.
✔ Detecting persistent resources [7623ms]
✘ Cleaning Up [110ms]
```
The idea is to remove the flag as the new strategy will be enabled by default.

feat: Add flag to enable managed variables

---

examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6328
This PR enables the `default` value for rich parameters with predefined options.

feat: Enable default value for rich parameter options

---

docs/data-sources/parameter.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6100
This PR adds a new computed property to `coder_parameter`, `optional`.
Analogically to [Terraform variables](https://servian.dev/terraform-optional-variables-and-attributes-using-null-and-optional-flag-62c5cd88f9ca) - a parameter is considered to be required if it doesn't have a `default` property, or it's `= null`. An empty string is an acceptable value, and it means that the parameter is not required.

feat: mark coder_parameter as optional

---

docs/data-sources/parameter.md
examples/resources/coder_parameter_migration/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6368
This PR adds new property to `coder_parameter` - `legacy_variable_name`.
It's outcome of the research [here](https://github.com/coder/coder/issues/6368#issuecomment-1462307379).

feat: Add legacy_variable_name to parameter

---

docs/data-sources/parameter.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6582
This PR adds another supported type to `coder_parameter`, a list of strings.

feat: support list(string) as coder_parameter

---

provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6582
This PR adds validation for a list of strings. I forgot to enable it in the previous PR.

feat: add validation for list(string)

---

provider/decode_test.go
provider/parameter.go

Related: https://github.com/coder/coder/issues/6734
This PR fixes the default `mapstructure` field annotation, which is different compared to Terraform resource attributes.

fix: annotate multi-words fields

---

provider/decode_test.go
provider/parameter.go

This PR fixes a bug introduced in https://github.com/coder/terraform-provider-coder/pull/118.
`display_name` field requires `mapstructure` annotation due to underscores.

fix: add mapstructure annotation to display_name

---

provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/7582
This PR fixes the invalid validation error message, show ptr instead of the value.

fix: show correct min and max values in validation errors

---

docs/resources/agent.md
provider/agent.go
provider/agent_test.go

Replace `login_before_ready` with `startup_script_behavior`

---

docs/data-sources/git_auth.md
docs/data-sources/parameter.md
docs/data-sources/provisioner.md
docs/data-sources/workspace.md
docs/resources/agent.md
docs/resources/agent_instance.md
docs/resources/app.md
docs/resources/metadata.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/8193
This PR adds `order` property to `coder_parameter` to determine the position of parameters presented in the UI/CLI form. More details can be found in the related issue.

feat: add order to coder_parameter

---

docs/data-sources/parameter.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6828#issuecomment-1621831139
This PR adds new property for coder parameter - `ephemeral`. Values of ephemeral parameters are not persisted between workspace builds and can be just set for the current build.

feat: support ephemeral parameters

---

examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/6828
This PR introduces another constraint for ephemeral parameters:
* ephemeral parameters can't be marked as required, so they must have the `default` property defined.

feat: ephemeral parameters must be optional

---

.github/workflows/release.yml

I believe it was mistakenly left out.

chore: bump go to 1.20 in release.yml

---

docs/resources/app.md
provider/app.go

A user has suggested to clarify the format of `url` in `coder_app` resource.
See : https://github.com/coder/coder/discussions/8574#discussioncomment-6486344 for related discussion.

chore: calrify the format of `url` for `coder_app` resource

---

provider/script.go
provider/script_test.go

Previously, this would just silently push the script and it would never run, because it wasn't configured to do so.
This changes it so all scripts have to be ran at some point.

fix: validate that `coder_script` has a way to run

---

docs/data-sources/workspace.md
provider/workspace.go
provider/workspace_test.go

This PR exports `template_version` in `coder_workspace` data source.
Requires https://github.com/coder/coder/pull/10306

feat(workspace): add the template version also

---

docs/resources/agent.md
examples/resources/coder_agent/resource.tf
provider/agent.go
provider/agent_test.go

Related: https://github.com/coder/coder/issues/8487
This PR adds `order` property to `coder_metadata`.

feat: add `order` property to agent_metadata

---

provider/agent.go

Related: https://github.com/coder/coder/pull/12066
While manually testing the coder implementation, I couldn't update the metadata (remove `order` property). The definition is missing `ForceNew`.

fix: metadata order with ForceNew

---

docs/resources/agent.md
provider/agent.go

this PR deprecates the `startup_script_timeout` & `shutdown_script_timeout` agent arguments in our provider documentation.

docs: deprecate startup_script_timeout & shutdown_script_timeout

---

provider/script.go
provider/script_test.go

This was originally part of #191 but split out because it is a bit of a breaking change, but hopefully it will help users avoid confusion when one is set without the other and the feature doesn't work.
This guarantee also makes our coder/coder more correct since it's common pratice to _only_ look at `start_blocks_login`.

fix!: add extra validation for start_blocks_login

---

docs/resources/app.md
provider/app.go

This clarifies where users may be confused about how to set an external URL, as the current description only talks about internal URL usage. 
Closes #186

chore: update description for `coder_app` `url`

---

docs/data-sources/parameter.md
provider/parameter.go
provider/parameter_test.go

Related: https://github.com/coder/coder/issues/12192
Right now, only string-typed parameters can use custom messages. This PR relaxes strict validation rules to support custom errors for number-typed coder parameters.

feat: relax error message for number-typed coder parameters

---

README.md
examples/resources/coder_parameter/resource.tf
provider/parameter.go
provider/parameter_test.go

Addresses https://github.com/coder/coder/issues/11579, PR in coder/coder will close
Currently we have a conflict declared between `option` and `validation` configs in `coder_parameter` Terraform resources (@mtojek do you have some historical context as to why that was the case?).
This PR removes that conflict since there is nothing inherent in the codebase disallowing them, and we need to allow both to to accommodate the use-case mentioned in the linked issue.
I expanded the tests and added documentation for testing the provider locally.

feat: allow `validation` to be used with `option`s

---

docs/resources/agent_instance.md
provider/provisioner.go
provider/provisioner_test.go

Fixes https://github.com/coder/coder/issues/11782
Tested on rpi 2b / armv7

fix(provider): coalesce arch to armv7 if on 32-bit arm

---

README.md
flake.lock
flake.nix

This installs
go: 1.20.12
terraform: 1.6.4
and is able to run all tests and build the provider.

chore: add a minimal nix flake

---

examples/resources/coder_workspace_tags/resource.tf
provider/examples_test.go
provider/provider.go
provider/workspace_tags.go
provider/workspace_tags_test.go

Related: https://github.com/coder/coder/issues/13218
This PR adds Terraform definition for `coder_workspace_tags` with resource reference tests.

feat: support workspace tags

---

.github/workflows/test.yml
integration/integration_test.go

Actually run the integration test!

ci: run integration test 

---

provider/helpers/env.go
provider/workspace.go
provider/workspace_test.go

Fixes: https://github.com/coder/terraform-provider-coder/issues/217
Related: https://github.com/coder/coder/pull/13680
This PR enables constraint validation for required environment variables.

feat: require environment variables

---

go.mod
go.sum
integration/integration_test.go

Previously, testing with coder versions older than 2.7 would fail due to the `template push` command not creating the template automatically.
Also, improves logic around pulling the image if it does not exist locally.

chore: improve integration test compatibility with older Coder versions

---

.github/workflows/test.yml

As per https://endoflife.date/terraform, only versions 1.8 and 1.9 are supported now. We can test from 1.5.x onwards for users who last upgraded about a year ago.

ci: drop terraform versions < 1.5.x, add 1.9.x for tests

---

docs/index.md
provider/provider.go

The `feature_use_managed_variables` option has been removed as Terraform variables are now exclusively utilized for template-wide variables. This commit removes the deprecated option from the provider code.
contributes to #250

chore!: remove deprecated feature_use_managed_variables

---

docs/index.md
templates/index.md.tmpl

This pull request adds a description to the provider index page. 
Closes #270

docs: add description to provider index page

---

docs/resources/metadata.md
provider/metadata.go

Backports only the changes in #267 to 1.0.

backport(docs): clarify coder_metadata usage

---

docs/resources/metadata.md
provider/metadata.go

The `coder_metadata` resource is only used to apply metadata to specific template resources. To apply metadata at the workspace level, and have it be shown on the main workspace pane, a `metadata` block needs to be created on the `coder_agent` resource.  Alternatively, any `coder_metadata` attached to the resource containing the agent will be shown on the dashboard by default (see our dogfood template), but this isn't super obvious, so we'll add a comment.
It's pretty easy to assume that the `coder_metadata` resource would let you apply workspace metadata, if you associated it with the agent, so we'll also add a comment mentioning this isn't the case.

docs: clarify `coder_metadata` usage

---

integration/integration_test.go

CI is currently failing and blocking PRs as the integration test running against Coder v2.15.0 (mainline) adds the "Everyone" group to the `workspace_owner` `groups` field. However, the CI also runs the integration test against Coder v2.14.2 (stable), which doesn't include the everyone group. 
We'll accept either an empty groups list, or a list with the everyone group to enable running the test against both versions.

fix: optional everyone group in integration test

---

provider/agent.go
provider/agent_test.go
provider/metadata.go
provider/metadata_test.go
provider/provider.go

Closes https://github.com/coder/coder/issues/14387.
Closes https://github.com/coder/coder/issues/14569.
Previously, the configuration had to be applied in order for the provider to complain about duplicate keys - now just a plan will suffice.

fix: validate agent & resource metadata keys during plan

---

integration/integration_test.go

backport #278
prerequisite for #280

backport(fix): optional everyone group in integration test

---

provider/agent.go
provider/agent_test.go
provider/metadata.go
provider/metadata_test.go
provider/provider.go

Backports #277 to `release/1.0`

backport(fix): validate agent & resource metadata keys during plan

---

integration/integration_test.go

Now cleans up the container when you Control+C!

chore(integration): cleanup on interrupt

---

docs/resources/app.md
integration/coder-app-hidden/main.tf
integration/integration_test.go
provider/app.go
provider/app_test.go

Relates to https://github.com/coder/coder/pull/14570
Adds a `hidden` field to the `coder_app` provider.

feat: add 'hidden' field to 'coder_app' provider

---

docs/resources/app.md
integration/coder-app-hidden/main.tf
integration/integration_test.go
provider/app.go
provider/app_test.go

Backporting https://github.com/coder/terraform-provider-coder/pull/276 to `release/1.0`

backport(feat): add 'hidden' field to 'coder_app' provider (#276)

---

docs/resources/app.md
provider/app.go

Document the minimum version of coder required for the 'hidden' attribute.

docs: document minimum version required for 'hidden' attribute

---

docs/resources/app.md
provider/app.go

Document the minimum version of coder required for the 'hidden' attribute.

backport(docs): document minimum version required for 'hidden' attribute

---

docs/data-sources/workspace_owner.md
integration/integration_test.go
integration/workspace-owner/main.tf
provider/workspace_owner.go
provider/workspace_owner_test.go

This PR add the login type the the `coder_workspace_owner` data source (Issue #235).
I took some decisions (like the default value to `none`), but if you think this should be different please let me know.
Thanks!

Add login_type to coder_workspace_owner data source #235

---

main.go
pprof_unix.go
pprof_windows.go

re: https://github.com/coder/coder/issues/14726
Adds a pprof goroutine dump listening on a unix domain socket at a well known path beneath the terraform work directory.  E.g. `/home/coder/.cache/coder/provisioner-0/work/.coder/pprof` with our default cache directory on coderd.
This should allow us to further diagnose the `text file busy` error, by seeing where things are hung in the goroutine dump.

chore: add http/pprof server over unix socket for debug

---

docs/guides/version-2-upgrade.md
docs/index.md
templates/guides/version-2-upgrade.md.tmpl
templates/index.md.tmpl

fix: fix links in version 2 upgrade guide

---

provider/workspace_owner.go

We no longer drop a diag.Warning if CODER_WORKSPACE_OWNER_LOGIN_TYPE is not set.

fix(provider): remove warning diag if CODER_WORKSPACE_OWNER_LOGIN_TYPE is not set

---

.goreleaser.yml

See: https://github.com/goreleaser/goreleaser/issues/4134

fix(.goreleaser.yml): use semver to sort git tags

---

go.mod
main.go
provider/agent.go
provider/decode_test.go
provider/externalauth.go
provider/parameter_test.go
provider/provider_test.go
provider/workspace.go
scripts/docsgen/main.go

We forgot to update the import paths when releasing v2! Doing so now as we'll probably need to import v2 of the provider in `coder/coder` eventually.

chore: update paths to /v2

---

README.md

Add a new section in the README to give details on how to release.

doc: add release section

---

docs/data-sources/parameter.md
examples/data-sources/coder_parameter/data-source.tf

fix(docs): fix parameter options icons

---

.github/workflows/test.yml

Drop support for EOL terraform versions. 
We upgraded to terraform 1.9 in Coder 2.14.x 7 months ago, which is no longer supported.
Also includes terraform 1.10

ci: drop support for EOL terraform version

---

provider/app.go
provider/app_test.go

Fixes: https://github.com/coder/terraform-provider-coder/issues/307
This PR enables basic validation for app display name: `coder_app` has database a constraint on the column length.

fix: app display name validation

---

docs/data-sources/parameter.md
provider/parameter.go
provider/parameter_test.go

Fixes: https://github.com/coder/terraform-provider-coder/issues/161
In coder/coder there is [no limitation](https://github.com/coder/coder/blob/d52d2397ea2c2fdb8636b966e3f45a0e26b7529d/coderd/database/dump.sql#L1215C1-L1235C1) for parameter options, and there is no real objective to have this limited enforced in terraform-provider-coder. This PR relaxes the constraint.
_I'm doing some spring cleanup around old issues._

fix: support unlimited parameter options

---

.goreleaser.yml

This configures goreleaser to automate prereleases when we push a tag that contains `pre` or `rc`
Ref: https://goreleaser.com/customization/release/#github

chore: test auto prerelease

---

.goreleaser.yml

Removes automatic handling of GitHub releases.
For some reason, the registry isn't recognizing new tags, and we suspect this might not be the cause.

chore: do not use GitHub prereleases

---

.github/workflows/release.yml

We've generally been lucky that builds are slower than integration tests, but we need explicit ordering here

chore: only release if tests pass

---

docs/data-sources/workspace_owner.md
integration/integration_test.go
integration/workspace-owner-filled/main.tf
integration/workspace-owner/main.tf
provider/workspace_owner.go
provider/workspace_owner_test.go

This PR updates the schema for the coder_workspace_owner data source to expose rbac_roles.
It's very similar to https://github.com/coder/terraform-provider-coder/pull/287
Relevant `coder/coder` PR - https://github.com/coder/coder/pull/16407

feat: add `rbac_roles` to `coder_workspace_owner` data source

---

README.md
docs/data-sources/workspace.md
docs/data-sources/workspace_preset.md
integration/integration_test.go
integration/test-data-source/main.tf
provider/workspace.go
provider/workspace_preset.go
provider/workspace_preset_test.go

This PR closes https://github.com/coder/terraform-provider-coder/issues/362

feat: allow presets to define prebuilds

---

provider/workspace_preset.go

As documented in the updated code, prebuilds require a slice in the type definition to allow terraform parsing tools to use our defined types and avoid duplication or drift.

fix: correct the prebuilds type definition

---

provider/formtype.go

To be backwards compatible using this repo as a library, use a string alias. This allows using the 'type' as a `string` or the new enum. Since enum validation is quite weak in Go, this is baiscally functionally equvialent.
This fixes a compile time issue in `coder/coder` when using the latest of this repo.

chore: change OptionType to alias for usage as string

---

go.mod

see: https://github.com/coder/terraform-provider-coder/pull/380#discussion_r2044082633

chore: update to go 1.24.1

---

provider/parameter_test.go
provider/testdata/parameter_table.md

Some of these cases you would expect it to be an error, but the validation passes

test: add more validation test cases

---

provider/parameter.go
provider/parameter_test.go
provider/testdata/parameter_table.md

Centralizes all validation logic into a single function on the parameter. This is intended to be imported by other packages (eg: preview) to do clientside validation before running terraform.
See diff from `main`. Left side is the tests passing on `main`.
https://www.diffchecker.com/GaUlaTze/
- Input values **must** be in the option set. [Before](https://github.com/coder/terraform-provider-coder/blob/a2bb4c074b3257ac7e2fd361b7dea1cadf954206/provider/testdata/parameter_table.md?plain=1#L49) this was allowed, but enforced in `coder/coder`
- Number parameters require values to be numbers. [Before](https://github.com/coder/terraform-provider-coder/blob/a2bb4c074b3257ac7e2fd361b7dea1cadf954206/provider/testdata/parameter_table.md?plain=1#L43) this was allowed, but enforced in `coder/coder`
- …

feat: parameter validation refactored to single function

---

provider/parameter.go
provider/parameter_test.go
provider/testdata/parameter_table.md

Previous value must come from env var. This change has to be made in `coder/coder` to take advantage of this.
[`CODER_PARAMETER_PREVIOUS_<hash>`](https://github.com/coder/terraform-provider-coder/blob/e011f733bf27b0f3daf58838fc3c4531d7b4e36c/provider/parameter.go#L697-L697)
Unfortunately reading from `tfstate` requires the block to be a `resource` block. This is because a `data` block only has access to the `Read` context.
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/resource.go#L287-L354
Read
> // The *ResourceData parameter contains the state data for this managed
// resource instance or data resource instance.
Update
> // The *ResourceData parameter contains the plan and state data for this
// managed resource instance. The available data in the Get* …

feat: enforce monotonicity in terraform provider 

---

docs/data-sources/workspace_preset.md
provider/workspace_preset.go

This PR adds a link from the schema documentation for prebuilt workspaces in this provider to the official user documentation of prebuilt workspaces.

docs: link to additional documentation for prebuilt workspaces

---

docs/data-sources/workspace.md
provider/workspace.go
provider/workspace_test.go

Template authors may need to augment their templates to execute scripts once a prebuilt workspace has been claimed.
`is_prebuild_claim` will be set **only** when a prebuilt workspace has just been claimed and its subsequent `terraform apply` is in progress.
Also adds some missing tests to ensure correct input (environment variables) handling.
Can be used in a template like so:
```terraform
resource "coder_agent" "main" {
arch           = data.coder_provisioner.me.arch
os             = "linux"
startup_script = <<-EOT
set -e
if [[ "${data.coder_workspace.me.is_prebuild}" = "true" ]]; then
echo "Created at $(date)" > ~/.prebuild_note # persists across restarts
fi
EOT
metadata {
display_name = "Was Prebuild"
key          = "prebuild"
script       = "[[ -e ~/.prebuild_note ]] && echo 'Yes' || …
```

feat: expose `is_prebuild_claim` attribute

---

.gitignore
docs/resources/agent.md
examples/resources/coder_agent/resource.tf
flake.lock
flake.nix
provider/agent.go
provider/agent_test.go

Part of https://github.com/coder/coder/issues/17649
---
This PR introduces a new `api_key_scope` parameter for the `coder_agent` resource, allowing administrators to control what API routes an agent token can access. This feature enhances security by providing the option to restrict sensitive user data access.
The new parameter supports two options:
- `all`: Full API access (this is the default value)
- `no_user_data`: Blocks access to `/external-auth`, `/gitsshkey`, and `/gitauth` routes
- Added the `api_key_scope` field to the agent resource schema with validation
- Updated documentation to reflect the new parameter
- Added comprehensive tests for valid transitions and invalid values
- Updated examples to demonstrate usage
- Added direnv configuration for improved developer experience
- …

Add agent API key scope to restrict access to user data

---

README.md

Update README instructions in the `Building` section to include the correct module path (`/v2` suffix) for `terraform-provider-coder`, as defined in its `go.mod`, when using `go mod edit`.

docs: update README note for local provider testing with correct module path

---

docs/data-sources/workspace_preset.md
integration/integration_test.go
integration/test-data-source/main.tf
provider/workspace_preset.go
provider/workspace_preset_test.go

This PR adds Terraform support for configuring a `expiration_policy` field in a template preset. This allows users to specify a TTL (`ttl`) for prebuild workspaces, after which they are considered expired and eligible for deletion and replacement.
* Updated the Terraform template preset resource to include the new `expiration_policy` block.
* Added validation and tests to ensure correct TTL handling.
```
prebuilds = {
instances = 2
expiration_policy {
ttl = 86400
}
}
```
Related:
* Required for https://github.com/coder/coder/pull/17996
* Related to https://github.com/coder/coder/issues/17916

feat: add expiration_policy parameter to prebuild resource

---

docs/data-sources/parameter.md
docs/resources/agent.md
docs/resources/app.md
docs/resources/devcontainer.md
provider/agent.go
provider/app.go
provider/devcontainer.go
provider/parameter.go

- Update the markdown for clearer inline code formatting
- Convert version requirements for `devcontainer` resource into an alert
- Refactor parameter type descriptions for consistency

docs: various documentation formatting improvements

---

provider/workspace_preset.go
provider/workspace_preset_test.go

This PR improves validation for the `expiration_policy.ttl` field in the Terraform schema by allowing an explicit value of `0` to disable expiration, while also enforcing a valid range of 3600 seconds (1 hour) to 31536000 seconds (1 year) for all other values. This ensures that prebuild TTLs are not configured with values that are too short, which could lead to premature expiration and unnecessary prebuild churn.
* Replaced validation.IntBetween with a custom validation function.
* TTL is now allowed to be:
* `0` disables expiration
* Between `3600` and `31536000` to enforce TTL values between 1 hour and 1 year.
No functional changes beyond input validation.
Related to: https://github.com/coder/terraform-provider-coder/pull/404

chore: add minimum TTL value for expiration.policy.ttl

---

provider/app.go
provider/app_test.go
provider/helpers/validation.go
provider/helpers/validation_test.go
provider/metadata.go
provider/parameter.go
provider/parameter_test.go
provider/provider.go

Fixes incorrect URL validation logic previously used in URL definitions, where the attribute label (`s`) was being parsed instead of the actual value. This bug caused invalid URLs to be silently accepted.
Additionally, this PR introduces a shared `ValidateURL` helper function to remove duplication and ensure consistent behavior across all URL fields.
- Fixed incorrect use of `url.Parse(s)`, now validating the actual value.
- Added `ValidateURL` helper function for consistent and reusable validation.
- Updated all schema definitions that perform URL validation to use `ValidateURL`.
- Adjusted tests to match the corrected validation logic.

fix: correct URL validation and centralize logic

---

docs/resources/app.md
examples/resources/coder_app/resource.tf
provider/app.go
provider/app_test.go

In this pull request we're adding an optional `tooltip` field. The `tooltip` field is a string field (with markdown support) that will be used to display tooltips on hover over app buttons in a workspace dashboard.
Tooltip screenshot
Tooltip video
https://github.com/user-attachments/assets/58c5d181-06bf-409f-b44c-5e92665664b4
Issue: https://github.com/coder/coder/issues/18431
Related coder PR: https://github.com/coder/coder/pull/19651
- Added `tooltip` to the `app` schema with a max length of 2048 characters
- Updated `app` documentation to include the `tooltip` field
- Added an example `tooltip`
- Added tests for empty, valid, and max length (to test validation logic)

feat: add tooltip field to workspace app

---

provider/agent.go
provider/agent_test.go

Fixes: https://github.com/coder/terraform-provider-coder/issues/432
There is a panic risk in `resources_monitoring" if the admin leaves an empty block without monitors.
Note: I wasn't able to reproduce the issue without `resources_monitoring`.

fix: do not panic if monitors undefined
